-- =========================================================
-- Migration: event_log + floor_code (+ 소소한 보강)
-- Idempotent, PG >= 11 가정 (IDENTITY / metadata-only DEFAULT)
-- =========================================================
BEGIN;

-- 1) 폴링 이벤트 소스
CREATE TABLE IF NOT EXISTS event_log (
  event_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  type           TEXT NOT NULL,              -- 'items.created' | 'inspection.opened' ...
  resource_id    BIGINT REFERENCES resources(resource_id) ON DELETE SET NULL,
  floor_code     TEXT,                       -- 응답/이벤트에 포함
  correlation_id TEXT,
  data           JSONB NOT NULL              -- EventEnvelope.data (앱에서 스키마 검증)
);
CREATE INDEX IF NOT EXISTS idx_eventlog_id          ON event_log(event_id);
CREATE INDEX IF NOT EXISTS idx_eventlog_res_id_id   ON event_log(resource_id, event_id);
CREATE INDEX IF NOT EXISTS idx_eventlog_created_desc ON event_log(created_at DESC);

-- 2) resources.floor_code 추가 (+ 백필 → NOT NULL → 인덱스)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name='resources' AND column_name='floor_code'
  ) THEN
    ALTER TABLE resources ADD COLUMN floor_code TEXT;              -- 일단 NULL 허용
  END IF;

  -- 기존 행 백필: 기본 'F1' (추후 실제 층 코드로 UPDATE 권장)
  UPDATE resources SET floor_code='F1' WHERE floor_code IS NULL;

  -- NOT NULL 제약 (백필 이후)
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid='resources'::regclass AND conname='resources_floor_code_not_null'
  ) THEN
    ALTER TABLE resources
      ALTER COLUMN floor_code SET NOT NULL,
      ADD CONSTRAINT resources_floor_code_not_null CHECK (floor_code IS NOT NULL);
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_resources_floor ON resources(floor_code);

-- 3) 락 GC 성능 보강
CREATE INDEX IF NOT EXISTS idx_resource_locks_expire ON resource_locks(expires_at);

-- 4) 조정 벌점 0 금지
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid='penalties_adjustments'::regclass
      AND conname='ck_pa_nonzero_delta'
  ) THEN
    ALTER TABLE penalties_adjustments
      ADD CONSTRAINT ck_pa_nonzero_delta CHECK (delta_points <> 0);
  END IF;
END$$;

-- 5) (선택) 권한 부여: dcs_app / dcs_read 있을 때만
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dcs_app') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON event_log TO dcs_app';
    EXECUTE 'ALTER TABLE event_log ENABLE ROW LEVEL SECURITY';        -- 필요시 비활성화/정책 추가
    -- 참고: RLS 쓸 계획 없으면 위 줄은 삭제해도 됨
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dcs_read') THEN
    EXECUTE 'GRANT SELECT ON event_log TO dcs_read';
  END IF;
END$$;

COMMIT;

-- 사용 예시(폴링):
--   SELECT * FROM event_log
--   WHERE event_id > $1             -- sinceId 커서
--     AND ($2::bigint IS NULL OR resource_id=$2)   -- 선택: 특정 자원
--     AND ($3::text   IS NULL OR floor_code=$3)    -- 선택: 특정 층
--   ORDER BY event_id ASC
--   LIMIT $4;
-- =========================================================
