/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DormMate 로그인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 로그인 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 리프레시 토큰으로 세션 갱신 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description 갱신 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 리프레시 토큰 폐기 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description 로그아웃 완료 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 로그인 사용자 정보 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 사용자 프로필 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 냉장고 슬롯 목록 조회 */
        get: {
            parameters: {
                query?: {
                    /** @description 조회할 층 (지정하지 않으면 전체) */
                    floor?: number;
                    /** @description full 지정 시 용량·표시 이름·점유 수 등 상세 정보를 포함 */
                    view?: "basic" | "full";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 슬롯 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FridgeSlot"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/compartments/{compartmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 냉장고 칸 설정 수정 */
        patch: operations["updateFridgeCompartment"];
        trace?: never;
    };
    "/admin/fridge/compartments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 냉장고 칸 메타데이터 조회 */
        get: {
            parameters: {
                query?: {
                    /** @description 조회할 층 (기본 2층) */
                    floor?: number;
                    /** @description full 시 displayName, label 범위, 용량 정보 포함 */
                    view?: "basic" | "full";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 칸 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FridgeSlot"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 포장 목록 조회 */
        get: {
            parameters: {
                query?: {
                    /** @description 특정 칸(슬롯)만 필터링 */
                    slotId?: string;
                    /** @description me 지정 시 내 포장만 반환 */
                    owner?: "me" | "all";
                    /** @description deleted 지정 시 소프트 삭제 포함 */
                    status?: "active" | "deleted";
                    /** @description 포장명/물품명/라벨(A123) 검색 */
                    search?: string;
                    /** @description 페이지 인덱스 (0부터 시작) */
                    page?: number;
                    /** @description 페이지 당 항목 수 */
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 포장 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BundleListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 새 포장 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBundleRequest"];
                };
            };
            responses: {
                /** @description 생성 완료 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateBundleResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/bundles/deleted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 삭제된 포장 이력 조회
         * @description 기본적으로 최근 3개월 이내 삭제된 포장을 반환하며, `since` 파라미터로 기간을 확장할 수 있습니다.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 조회 기준 시각(UTC). 지정하지 않으면 현재 시각 기준 3개월 전으로 자동 설정됩니다. */
                    since?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제된 포장 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BundleListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/reallocations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 층별 칸-호실 재배분 추천안 조회
         * @description 현재 배정 현황을 바탕으로 균등 분배한 추천안을 생성합니다. 실제 반영 전 검토용으로 사용하세요.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReallocationPreviewRequest"];
                };
            };
            responses: {
                /** @description 추천안 생성 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReallocationPreviewResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/reallocations/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 층별 칸-호실 재배분 확정 반영
         * @description 검토·수정한 배정안을 저장하고 기존 배정을 종료합니다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReallocationApplyRequest"];
                };
            };
            responses: {
                /** @description 재배분 적용 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReallocationApplyResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 알림 목록 조회
         * @description 미읽음 우선 정렬로 알림을 반환합니다. TTL이 지난 알림은 자동으로 만료 처리됩니다.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 조회할 알림 상태 */
                    state?: "all" | "unread" | "read";
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 알림 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 특정 알림 읽음 처리 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notificationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 읽음 처리 완료 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 모든 미읽음 알림 읽음 처리 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 처리 완료 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 알림 수신 설정 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 알림 선호 설정 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationPreferenceResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preferences/{kindCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 알림 수신 설정 변경 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 알림 종류 코드 (예: FRIDGE_RESULT) */
                    kindCode: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNotificationPreferenceRequest"];
                };
            };
            responses: {
                /** @description 변경된 설정 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationPreferenceItem"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/fridge/bundles/{bundleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        /** 포장 상세 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bundleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 포장 상세 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FridgeBundle"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** 포장 삭제(소프트 삭제) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bundleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 완료 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** 포장 정보 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bundleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBundleRequest"];
                };
            };
            responses: {
                /** @description 수정된 포장 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FridgeBundle"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        trace?: never;
    };
    "/fridge/bundles/{bundleId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 포장에 물품 추가 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bundleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddItemRequest"];
                };
            };
            responses: {
                /** @description 추가된 물품 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FridgeItem"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 물품 삭제(소프트) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 완료 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** 물품 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateItemRequest"];
                };
            };
            responses: {
                /** @description 수정된 물품 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FridgeItem"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        trace?: never;
    };
    "/fridge/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 검사 세션 목록 조회 */
        get: {
            parameters: {
                query?: {
                    /** @description 특정 칸의 세션만 조회 */
                    slotId?: string;
                    /** @description 세션 상태 필터 */
                    status?: "IN_PROGRESS" | "SUBMITTED" | "CANCELLED";
                    /** @description 반환할 최대 세션 수 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 검사 세션 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InspectionSession"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 검사 세션 시작 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        slotId: string;
                    };
                };
            };
            responses: {
                /** @description 생성된 검사 세션 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InspectionSession"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 검사 세션 조회 */
        get: {
            parameters: {
                query?: {
                    /** @description 특정 층 기준으로 필터링 */
                    floor?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 진행 중인 세션 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InspectionSession"];
                    };
                };
                /** @description 진행 중인 세션 없음 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        /** 검사 세션 상세 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 검사 세션 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InspectionSession"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** 검사 세션 취소 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 취소 완료 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/{sessionId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 검사 조치 기록 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InspectionActionRequest"];
                };
            };
            responses: {
                /** @description 갱신된 세션 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InspectionSession"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/{sessionId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 검사 결과 제출 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SubmitInspectionRequest"];
                };
            };
            responses: {
                /** @description 제출 완료된 세션 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InspectionSession"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 폴링 커서 조회
         * @description sinceId 이후 이벤트를 event_id 오름차순으로 반환한다.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 마지막으로 수신한 eventId. 빈 값이면 최신 50개를 반환한다. */
                    sinceId?: number;
                    /** @description 한번에 받을 이벤트 수 상한 */
                    limit?: number;
                    /** @description 특정 리소스(event_log.resource_id) 필터 */
                    resourceId?: number;
                    /** @description 층 코드 필터 (예: 2F) */
                    floor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 이벤트 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PollResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
                /** @description 세션 잠금 상태 */
                423: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
        /** @enum {string} */
        RoleCode: "RESIDENT" | "FLOOR_MANAGER" | "ADMIN";
        TokenPair: {
            /** @description 서명된 JWT 액세스 토큰 */
            accessToken: string;
            /**
             * @default Bearer
             * @enum {string}
             */
            tokenType: "Bearer";
            /**
             * Format: int64
             * @description 액세스 토큰 만료까지 남은 초
             */
            expiresIn: number;
            refreshToken: string;
            /**
             * Format: int64
             * @description 리프레시 토큰 만료까지 남은 초
             */
            refreshExpiresIn: number;
            /** Format: date-time */
            issuedAt: string;
        };
        LoginRequest: {
            loginId: string;
            /** Format: password */
            password: string;
            /** @description 다중 디바이스 토큰 관리용 식별자 */
            deviceId?: string | null;
        };
        LoginResponse: {
            tokens: components["schemas"]["TokenPair"];
            user: components["schemas"]["UserProfile"];
        };
        RefreshRequest: {
            refreshToken: string;
            deviceId?: string | null;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        RoomAssignment: {
            /** Format: uuid */
            roomId: string;
            floor: number;
            roomNumber: string;
            personalNo: number;
            /** Format: date-time */
            assignedAt: string;
        };
        UserProfile: {
            /** Format: uuid */
            userId: string;
            loginId: string;
            displayName: string;
            /** Format: email */
            email?: string | null;
            roles: components["schemas"]["RoleCode"][];
            primaryRoom?: components["schemas"]["RoomAssignment"];
            isFloorManager: boolean;
            isAdmin: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        SlotType: "CHILL" | "FREEZE";
        /** @enum {string} */
        ResourceStatus: "ACTIVE" | "SUSPENDED" | "REPORTED" | "RETIRED";
        FridgeSlot: {
            /** Format: uuid */
            slotId: string;
            slotIndex: number;
            slotLetter: string;
            floorNo: number;
            floorCode: string;
            compartmentType: components["schemas"]["SlotType"];
            resourceStatus: components["schemas"]["ResourceStatus"];
            locked: boolean;
            /** Format: date-time */
            lockedUntil?: string | null;
            capacity?: number | null;
            displayName?: string | null;
            occupiedCount?: number | null;
        };
        UpdateCompartmentConfigRequest: {
            maxBundleCount?: number;
            status?: components["schemas"]["ResourceStatus"];
        };
        /** @enum {string} */
        ItemFreshness: "ok" | "expiring" | "expired";
        FridgeItem: {
            /** Format: uuid */
            itemId: string;
            /** Format: uuid */
            bundleId: string;
            name: string;
            /** Format: date */
            expiryDate: string;
            quantity?: number | null;
            unitCode?: string | null;
            freshness: components["schemas"]["ItemFreshness"];
            /** Format: date-time */
            lastInspectedAt?: string | null;
            updatedAfterInspection: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            removedAt?: string | null;
        };
        /** @enum {string} */
        BundleStatus: "ACTIVE" | "DELETED";
        FridgeBundleSummary: {
            /** Format: uuid */
            bundleId: string;
            /** Format: uuid */
            slotId: string;
            slotIndex: number;
            slotLabel: string;
            labelNumber: number;
            labelDisplay: string;
            bundleName: string;
            memo?: string | null;
            /** Format: uuid */
            ownerUserId?: string;
            ownerDisplayName?: string | null;
            ownerRoomNumber?: string | null;
            status: components["schemas"]["BundleStatus"];
            /** @enum {string} */
            freshness: "ok" | "expiring" | "expired";
            itemCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            removedAt?: string | null;
        };
        FridgeBundle: components["schemas"]["FridgeBundleSummary"] & {
            items: components["schemas"]["FridgeItem"][];
        };
        BundleListResponse: {
            items: components["schemas"]["FridgeBundleSummary"][];
            /** Format: int64 */
            totalCount: number;
        };
        ReallocationPreviewRequest: {
            /** Format: int32 */
            floor: number;
        };
        ReallocationPreviewResponse: {
            /** Format: int32 */
            floor: number;
            rooms: components["schemas"]["ReallocationRoomSummary"][];
            allocations: components["schemas"]["ReallocationCompartmentAllocation"][];
            /** Format: int32 */
            chillCompartmentCount: number;
        };
        ReallocationRoomSummary: {
            /** Format: uuid */
            roomId: string;
            roomNumber: string;
            roomType: string;
            /** Format: int32 */
            floor: number;
        };
        ReallocationCompartmentAllocation: {
            /** Format: uuid */
            compartmentId: string;
            /** Format: uuid */
            fridgeUnitId: string;
            /** Format: int32 */
            slotIndex: number;
            slotLabel: string;
            /** @enum {string} */
            compartmentType: "CHILL" | "FREEZE";
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED" | "REPORTED" | "RETIRED";
            locked: boolean;
            currentRoomIds: string[];
            recommendedRoomIds: string[];
            warnings: string[];
        };
        ReallocationApplyRequest: {
            /** Format: int32 */
            floor: number;
            allocations: components["schemas"]["ReallocationApplyAllocation"][];
        };
        ReallocationApplyAllocation: {
            /** Format: uuid */
            compartmentId: string;
            roomIds: string[];
        };
        ReallocationApplyResponse: {
            /** Format: int32 */
            floor: number;
            /** Format: int32 */
            affectedCompartments: number;
            /** Format: int32 */
            releasedAssignments: number;
            /** Format: int32 */
            createdAssignments: number;
            /** Format: date-time */
            appliedAt: string;
        };
        /** @enum {string} */
        NotificationState: "UNREAD" | "READ" | "EXPIRED";
        NotificationItem: {
            /** Format: uuid */
            id: string;
            kindCode: string;
            title: string;
            body: string;
            state: components["schemas"]["NotificationState"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            readAt?: string | null;
            /** Format: date-time */
            ttlAt?: string | null;
            /** Format: uuid */
            correlationId?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
        };
        NotificationListResponse: {
            items: components["schemas"]["NotificationItem"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int64 */
            unreadCount: number;
        };
        NotificationPreferenceItem: {
            kindCode: string;
            displayName: string;
            description: string;
            enabled: boolean;
            allowBackground: boolean;
        };
        NotificationPreferenceResponse: {
            items: components["schemas"]["NotificationPreferenceItem"][];
        };
        UpdateNotificationPreferenceRequest: {
            enabled: boolean;
            allowBackground: boolean;
        };
        CreateBundleItemInput: {
            name: string;
            /** Format: date */
            expiryDate: string;
            quantity?: number | null;
            unitCode?: string | null;
        };
        CreateBundleRequest: {
            /** Format: uuid */
            slotId: string;
            bundleName: string;
            memo?: string | null;
            items: components["schemas"]["CreateBundleItemInput"][];
        };
        CreateBundleResponse: {
            bundle: components["schemas"]["FridgeBundle"];
        };
        UpdateBundleRequest: {
            bundleName?: string | null;
            memo?: string | null;
            /** Format: date-time */
            removedAt?: string | null;
        };
        AddItemRequest: {
            name: string;
            /** Format: date */
            expiryDate: string;
            quantity?: number | null;
            unitCode?: string | null;
        };
        UpdateItemRequest: {
            name?: string | null;
            /** Format: date */
            expiryDate?: string | null;
            quantity?: number | null;
            unitCode?: string | null;
            /** Format: date-time */
            removedAt?: string | null;
        };
        /** @enum {string} */
        InspectionStatus: "IN_PROGRESS" | "SUBMITTED" | "CANCELED";
        /** @enum {string} */
        InspectionAction: "WARN_INFO_MISMATCH" | "WARN_STORAGE_POOR" | "DISPOSE_EXPIRED" | "PASS" | "UNREGISTERED_DISPOSE";
        InspectionActionSummary: {
            action: components["schemas"]["InspectionAction"];
            count: number;
        };
        InspectionActionItem: {
            /** Format: int64 */
            id?: number;
            /** Format: uuid */
            fridgeItemId?: string | null;
            snapshotName?: string | null;
            /** Format: date */
            snapshotExpiresOn?: string | null;
            quantityAtAction?: number | null;
        };
        PenaltyHistory: {
            /** Format: uuid */
            id?: string;
            points?: number;
            reason?: string | null;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        InspectionActionDetail: {
            /** Format: int64 */
            actionId?: number;
            actionType?: components["schemas"]["InspectionAction"];
            /** Format: uuid */
            bundleId?: string | null;
            /** Format: uuid */
            targetUserId?: string | null;
            /** Format: date-time */
            recordedAt?: string;
            /** Format: uuid */
            recordedBy?: string | null;
            note?: string | null;
            items?: components["schemas"]["InspectionActionItem"][];
            penalties?: components["schemas"]["PenaltyHistory"][];
        };
        InspectionSession: {
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            slotId: string;
            slotIndex: number;
            slotLabel: string;
            floorNo: number;
            floorCode?: string | null;
            status: components["schemas"]["InspectionStatus"];
            /** Format: uuid */
            startedBy: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string | null;
            bundles: components["schemas"]["FridgeBundle"][];
            summary: components["schemas"]["InspectionActionSummary"][];
            actions?: components["schemas"]["InspectionActionDetail"][];
            notes?: string | null;
        };
        InspectionActionEntry: {
            /** Format: uuid */
            bundleId?: string | null;
            /** Format: uuid */
            itemId?: string | null;
            action: components["schemas"]["InspectionAction"];
            note?: string | null;
        };
        InspectionActionRequest: {
            actions: components["schemas"]["InspectionActionEntry"][];
        };
        SubmitInspectionRequest: {
            notes?: string | null;
        };
        PollEvent: {
            /** Format: int64 */
            eventId: number;
            type: string;
            /** Format: int64 */
            resourceId?: number | null;
            floorCode?: string | null;
            data: string;
            correlationId?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
        };
        PollResponse: {
            /** Format: int64 */
            lastId: number;
            events: components["schemas"]["PollEvent"][];
        };
    };
    responses: {
        /** @description 잘못된 요청 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 인증 실패 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 권한 부족 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 리소스를 찾을 수 없음 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 처리 충돌 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 비즈니스 규칙 위반 */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 요청 한도 초과 */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateFridgeCompartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compartmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCompartmentConfigRequest"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FridgeSlot"];
                };
            };
            /** @description 관리자 권한 필요 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 칸을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 검사 세션이 진행 중인 칸은 상태를 변경할 수 없음 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 현재 활성 포장 수보다 낮게 용량을 설정할 수 없음 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
